### ISSUE TITLE
翻译没反应？

### ISSUE THREAD

**Issue by howie6879** [waynecz/dadda-translate-crx#220]
![image](https://user-images.githubusercontent.com/17047388/63816920-9978ea00-c96c-11e9-8bd4-3c78f18ab1ee.png)

**Comment by waynecz** [comment]
搜狗 API 变动，正在修复

**Comment by Kealina-A** [comment]
双击也翻译不了了

**Comment by mowozy** [comment]
翻译服务器挂了？

**Comment by Holybasil** [comment]
wait

**Comment by waynecz** [comment]
@howie6879 @Kealina-A @mowozy @Holybasil    修复版本已经发布: [v1.2.6](https://github.com/waynecz/dadda-translate-crx/releases/tag/v1.2.6)

**Comment by howie6879** [comment]
完美

**Comment by 00LT00** [comment]
威武

**Comment by Weeeendi** [comment]
好像又不行了 @waynecz

**Comment by waynecz** [comment]
@Weeeendi 我目前这边可以，提供下环境？浏览器版本，浏览网站，插件版本

**Comment by HeavenlyChorus** [comment]
我这又没反应了，Chrome 76.0.3809.132 64bit，插件版本1.2.6

**Comment by yjiaz** [comment]
今天又不能翻译了，和之前一样的情况

**Comment by Godiva0** [comment]
今天怎么又没有反应啦？神马情况啊？

**Comment by waynecz** [comment]
#224 搜狗被我写的 bug “攻击”了😂，猜测可能是拒绝了流量，大家先停用插件，等修复后再使用

**Comment by waynecz** [comment]
@HeavenlyChorus  @Weeeendi  @yjiaz  @Godiva0   修复版本 1.2.8 大概在一小时后过审可更新

**Comment by yumengbdw** [comment]
![image](https://user-images.githubusercontent.com/11400046/64395144-cbd0c880-d08b-11e9-8e47-50c1920ce515.png)
这两天出现的，求修复。

**Comment by waynecz** [comment]
@yumengbdw 重复了两条，所以删了一个，修复版本 1.2.8 大概在一小时后过审可更新

**Comment by yumengbdw** [comment]
> @yumengbdw 重复了两条，所以删了一个，修复版本 1.2.8 大概在一小时后过审可更新

已更新，解决，感谢！

**Comment by lzhuor** [comment]
Thank you! @waynecz

**Comment by yumengbdw** [comment]
> @yumengbdw 重复了两条，所以删了一个，修复版本 1.2.8 大概在一小时后过审可更新

划词还是不行

**Comment by waynecz** [comment]
@yumengbdw 个别网站不行还是全部不行了？

**Comment by g19980115** [comment]
我这也不行，全部没反应
![搜狗截图20190907103648](https://user-images.githubusercontent.com/25760230/64468808-75cb5600-d15b-11e9-9b84-67fad88b71a1.png)

**Comment by zbjdonald** [comment]
我这也不行，点了之后没反应，全部网站。1.2.8版本

**Comment by elliottzheng** [comment]
赞作者，坐等修复

**Comment by waynecz** [comment]
@g19980115 @zbjdonald 😢试着开启 go 模式看看能不能出来 <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>g</kbd>，还是不行的话在 chrome://extensions 下找到 达达插件，点击查看 background.js，划词后截个图看看(图2)

![image](https://user-images.githubusercontent.com/11238540/64496962-9e835500-d2ed-11e9-9ebd-11d1e1c75e86.png)

![image](https://user-images.githubusercontent.com/11238540/64496984-cecaf380-d2ed-11e9-801c-07fec28596e9.png)

**Comment by yumengbdw** [comment]
![image](https://user-images.githubusercontent.com/11400046/64497896-367c4100-d2e4-11e9-9c3d-7f6928df4f01.png)
![image](https://user-images.githubusercontent.com/11400046/64497994-befae180-d2e4-11e9-947d-87b44f9785a5.png)

以上两种划词部分英文或全部因为都会请求，但请求成功后没有弹框。只有达达的那个圆形 logo

如果划词全部中文不会请求。

**Comment by g19980115** [comment]
看到错误日志了
![TIM截图20190909095947](https://user-images.githubusercontent.com/25760230/64498802-d0de8380-d2e8-11e9-8db2-a69f86a9f021.png)


```
extensions::schemaUtils:34
Uncaught Error: Invalid value for argument 2. Property '.2': Value must be one of: [requestHeaders, blocking].
    at validate (extensions::schemaUtils:34:13)
    at validateListenerArguments (extensions::webRequestEvent:19:5)
    at WebRequestEventImpl.addListener (extensions::webRequestEvent:92:3)
    at WebRequestEvent.publicClassPrototype.(anonymous function) [as addListener] (extensions::utils:138:26)
    at Module.<anonymous> (chrome-extension://cajhcjfcodjoalmhjekljnfkgjlkeajl/background/background.js:15:7332)
    at n (chrome-extension://cajhcjfcodjoalmhjekljnfkgjlkeajl/background/background.js:1:110)
    at chrome-extension://cajhcjfcodjoalmhjekljnfkgjlkeajl/background/background.js:1:902
    at chrome-extension://cajhcjfcodjoalmhjekljnfkgjlkeajl/background/background.js:1:913

background.js:1 
Uncaught (in promise) TypeError: Cannot read property 'errorCode' of undefined
    at _client__WEBPACK_IMPORTED_MODULE_0__.c.post.then (background.js:1)
```

**Comment by g19980115** [comment]
每点击一次达达图标进行翻译，
```
background.js:1 
Uncaught (in promise) TypeError: Cannot read property 'errorCode' of undefined
    at _client__WEBPACK_IMPORTED_MODULE_0__.c.post.then (background.js:1)
```
这个错误次数就会加1

**Comment by lePig** [comment]
很奇怪的是 我的win7 chrome70 不行 

家里的mac chrome79 就正常没事呢

![14jU.png](https://u.vmpic.cn/2019/10/07/14jU.png)

**Comment by waynecz** [comment]
今天陆陆续续出现翻译乱码问题，正在排查。

**Comment by mdj456000** [comment]
本来是乱码，更新了一下chrome之后直接没有翻译框弹出来了

**Comment by mdj456000** [comment]
chrome版本77.0.3865.90，点翻译还是不出弹框，翻译接面也没有反应
![批注 2019-10-09 110607](https://user-images.githubusercontent.com/13214990/66448690-e9c38b80-ea84-11e9-8c2f-42841aa658c8.png)

**Comment by flystar233** [comment]
难受啊，乱码~~

**Comment by flystar233** [comment]
使用代理VPN之后可以正常翻译~关掉则乱码，不知道是什么原因

**Comment by waynecz** [comment]
已提交 1.2.10， 等待审核发布

**Comment by Niansi** [comment]
> ### UPDATE: 北京时间 2019-10-09 13:17
> 已发布 1.2.10

更新之后依然不能翻译，挂vpn就正常

**Comment by smackgg** [comment]
here~
1.翻译乱码依旧
2.单词页面点击翻译，页面布局出错了~截图如下

![image](https://user-images.githubusercontent.com/13075469/66459357-75e6aa80-eaa7-11e9-81e8-5f598331cbf0.png)

**Comment by taseikyo** [comment]
更新之后划词翻译没反应😶

**Comment by YuiTatsumi** [comment]
約昨晚開始翻譯沒反應，更新之後依舊沒反應

**Comment by Li7tleMK** [comment]
达达商店最新版本
Google Chrome 已是最新版本
版本 77.0.3865.90（正式版本） （64 位）
macOS 10.14.6

**Comment by CavinChan** [comment]
目前更新到1.2.10版本点翻译也没反应，希望作者大大再更新一下

**Comment by waynecz** [comment]
@CavinChan @Li7tleMK @YuiTatsumi @taseikyo @smackgg @Niansi 
Sorry 大家试着打开下 [https://fanyi.sogou.com/#auto/zh-CHS/check](https://fanyi.sogou.com/#auto/zh-CHS/check) 然后去其他网页使用插件试试

**Comment by waynecz** [comment]
@smackgg 可以加下你微信或者 telegram 不，需要一个志愿者排查BUG🤪

**Comment by mdj456000** [comment]
开着sogou页面就可以翻译，很奇怪

**Comment by waynecz** [comment]
@mdj456000  费尽力气只能打出一个 “？”

**Comment by smackgg** [comment]
@waynecz 微信发你邮箱了

**Comment by taseikyo** [comment]
> @CavinChan @Li7tleMK @YuiTatsumi @taseikyo @smackgg @Niansi
> Sorry 大家试着打开下 https://fanyi.sogou.com/#auto/zh-CHS/check 然后去其他网页使用插件试试，
> 
> 还是不行的话大家稍安勿躁，正在加紧的干活😂

打开之后要求输入验证码，输完之后就好了😂，没反应估计就因为验证码 233

**Comment by waynecz** [comment]
@taseikyo 看样子是IP被搜狗判定是机器人了太🀁🀁🀁🀁🀁🀁🀁🀁🀁🀁🀁🀁🀁🀁🀁🀁🀁🀁了

**Comment by YuiTatsumi** [comment]
驗證碼+1 輸入完就可以了！謝謝

**Comment by Niansi** [comment]
> @CavinChan @Li7tleMK @YuiTatsumi @taseikyo @smackgg @Niansi
> Sorry 大家试着打开下 https://fanyi.sogou.com/#auto/zh-CHS/check 然后去其他网页使用插件试试，
> 
> 还是不行的话大家稍安勿躁，正在加紧的干活😂

解决啦，果然是验证码

**Comment by jasonqiao36** [comment]
今天已经填了两次验证码了，有点麻烦

**Comment by g19980115** [comment]
还是不行诶，是不是这个错误的原因
![TIM截图20191011093751](https://user-images.githubusercontent.com/25760230/66618196-d93d1d80-ec0a-11e9-964f-bdd2ae89da79.png)

**Comment by myesn** [comment]
你好，  @howie6879 ，我非常喜欢这款插件，但最近两天总是频繁的输入验证码，插件基本上不可用，是因为我使用了代理软件，还是有其他原因？

**Comment by waynecz** [comment]
@myesn 应该是搜狗开始限流了...

**Comment by jeasonstudio** [comment]
@waynecz 希望尽快处理，已经很久了，如果搜狗源实在绕不过限流可以考虑换个别的

**Comment by yjiaz** [comment]
> @myesn 应该是搜狗开始限流了...

能否在插件中Github按钮边上增加直达搜狗翻译的按钮，刚刚遇上了用着用着触发验证码的情况，能不能加一个这样的快捷键方便过去？

**Comment by qiaoxueshi** [comment]
> @myesn 应该是搜狗开始限流了...

确实是限流了，直接跳转到了这里 
https://www.sogou.com/antispider/?from=https%3A%2F%2Ffanyi.sogou.com

**Comment by GONETHEN** [comment]
为什么不用谷歌？有道百度也行吧？

**Comment by yjiaz** [comment]
> 为什么不用谷歌？有道百度也行吧？

https://www.v2ex.com/t/430327

**Comment by GONETHEN** [comment]
> > 为什么不用谷歌？有道百度也行吧？
> 
> https://www.v2ex.com/t/430327

https://translate.google.cn/#view=home&op=translate&sl=auto&tl=zh-CN&text=Better%20late%20than%20never.%0A%0AThree%20days%20after%20the%20implosion%20of%20an%20exchange-traded%20note%20betting%20on%20low%20volatility%2C%20Fidelity%20Investments%20said%20it%20had%20moved%20to%20protect%20investors%20from%20these%20products.%0A%0AThe%20fund%20giant%20is%20halting%20customer%20purchases%20of%20three%20volatility-focused%20exchange%20traded%20funds%2C%20Robert%20Beauregard%2C%20a%20company%20spokesman%2C%20said%20in%20an%20email.%20They%20are%3A%20ProShares%20Short%20VIX%20Short-Term%20Futures%20(SVXY)%2C%20VelocityShares%20Daily%20Inverse%20VIX%20Short-Term%20ETN%20(XIV)%2C%20and%20the%20VelocityShares%20Daily%20Inverse%20VIX%20Medium%20Term%20ETN%20(ZIV).%0A%0AThe%20ban%20started%20Feb.%206%2C%20Beauregard%20said.%20The%20firm%20didn%20%E2%80%99%20t%20issue%20the%20news%20publicly%20until%20Friday.%20%E2%80%9C%20We%20are%20allowing%20customers%20to%20sell%20out%20of%20existing%20positions%2C%E2%80%9D%20he%20said.%0A%0ARepresentatives%20for%20TD%20Ameritrade%20Holding%20Corp.%20and%20Charles%20Schwab%20Corp.%20said%20Friday%20that%20customers%20can%20still%20trade%20SVXY.%20Ameritrade%2C%20however%2C%20is%20holding%20a%20100%20percent%20margin%20requirement%20for%20those%20purchases%2C%20spokeswoman%20Kim%20Hillyer%20said.%0A%0ABrokerage%20firms%20including%20E-Trade%20have%20moved%20to%20protect%20customers%20as%20global%20markets%20have%20plunged%20and%20volatility%20has%20surged.%20The%20fallout%20from%20the%20implosion%20of%20a%20vast%20array%20of%20arcane%20bets%20against%20stock-market%20volatility%20mounted%20this%20week.%20Credit%20Suisse%20Group%20AG%20moved%20to%20liquidate%20one%20investment%20product%20and%20more%20than%20a%20dozen%20others%20were%20halted%20after%20their%20values%20sunk%20toward%20zero.%0A%0ASVXY%20is%20down%2091%20percent%20since%20last%20Friday%2C%20XIV%20plunged%2096%20percent%20and%20ZIV%20fell%2027%20percent.%0A%0AThe%20Financial%20Times%20earlier%20reported%20on%20the%20Fidelity%20%E2%80%99%20s%20decision.%0A%0AFidelity%20said%20customers%20who%20want%20to%20buy%20funds%20that%20borrow%20money%20to%20increase%20their%20returns%20must%20sign%20an%20agreement%20that%20lays%20out%20the%20risks%20of%20the%20products%20and%20acknowledge%20that%20they%20have%20a%20%E2%80%9C%20most%20aggressive%20%E2%80%9D%20risk%20tolerance.

**Comment by qiaoxueshi** [comment]
> 为什么不用谷歌？有道百度也行吧？

搜狗的翻译质量比Google好，更比后两者好

**Comment by YuiTatsumi** [comment]
最近瘋狂出現驗證。如果不是取代搜狗翻譯的話，是否該有個第二或第三順位的其他家翻譯供選擇？騰訊翻譯君、彩雲小譯、百度翻譯、有道翻譯感覺都可以考慮。

**Comment by HSUTZUHAN** [comment]
网页翻译和输入框可以正常用，但pdf内划词右键点翻译没有反应
报错内容：
![image](https://user-images.githubusercontent.com/15816679/67208620-6c1a5b00-f448-11e9-85f6-70e180446260.png)

**Comment by KennyWho** [comment]
2019年了，就别说搜狗比谷歌翻译更好了，自己试试就知道了。目前解决方法就是浏览器开一个搜狗翻译输入验证码后别关掉，然后正常使用就可以了。

**Comment by jiaweiCao** [comment]
点了翻译直接没翻译。没报错。
扩展程序打开看到错误提示
![image](https://user-images.githubusercontent.com/40780661/67647848-a4e99100-f96e-11e9-92d0-f38238e82806.png)

**Comment by waynecz** [comment]
> 点了翻译直接没翻译。没报错。
> 扩展程序打开看到错误提示
> ![image](https://user-images.githubusercontent.com/40780661/67647848-a4e99100-f96e-11e9-92d0-f38238e82806.png)

请问是今天更新的 Chrome 么，插件版本是 1.2.15 ？

**Comment by jiaweiCao** [comment]
我直接手动下载的v1.2.12.crx。拉到拓展程序打不开

**Comment by jiaweiCao** [comment]
我直接手动下载的v1.2.12.crx。拉到拓展程序打不开
![image](https://user-images.githubusercontent.com/40780661/67648679-5be70c00-f971-11e9-8c4c-5cc5b27fcd0c.png)

**Comment by waynecz** [comment]
@jiaweiCao  https://github.com/waynecz/dadda-translate-crx/releases/download/v1.2.15/v1.2.15.crx

试下安装这个

**Comment by jiaweiCao** [comment]
我是直接手动下载的v1.2.12.crx，拉到拓展文件打不开
![image](https://user-images.githubusercontent.com/40780661/67648707-75885380-f971-11e9-910a-4456596d201f.png)
我就只接把后缀名改为.rar，用开发者模式选择加载已解压的拓展程序。
然后就会经常出现，点击了翻译没反应也不报错，然后在手动翻译处没反应的情况
![image](https://user-images.githubusercontent.com/40780661/67648861-d748bd80-f971-11e9-97bc-f2415d02bf77.png)

**Comment by jiaweiCao** [comment]
好的，可以了，谢谢作者

**Comment by taseikyo** [comment]
这个需要验证的提醒我觉得很棒😂
![TIM20191028165625](https://user-images.githubusercontent.com/23132915/67665083-f3655280-f9a3-11e9-92c6-364598dcad43.png)

**Comment by CavinChan** [comment]
安装了这个https://github.com/waynecz/dadda-translate-crx/releases/download/v1.2.15/v1.2.15.crx点翻译也还是没反应，Chrome已经更新到最新版了

**Comment by waynecz** [comment]
@CavinChan 试下这样：
1. 打开 https://fanyi.sogou.com 查看是否需要输入验证码
2. 打开 https://translate.google.cn 看是否能正常访问

**Comment by CavinChan** [comment]
> @CavinChan 试下这样：
> 
> 1. 打开 https://fanyi.sogou.com 查看是否需要输入验证码
> 2. 打开 https://translate.google.cn 看是否能正常访问

可以，谢谢作者大大

**Comment by CavinChan** [comment]
> @CavinChan 试下这样：
> 
> 1. 打开 https://fanyi.sogou.com 查看是否需要输入验证码
> 2. 打开 https://translate.google.cn 看是否能正常访问

求问能在PDF下右键使用吗？

**Comment by 00LT00** [comment]
我现在一直在输入验证码，但是还是会重复跳出来让我输入，是搜狗那边的问题吗，另外最新版支持谷歌的版本有没有上架google商店呢

**Comment by EdenSpark** [comment]
1.2.16版本，Chrome浏览器没问题，360极速浏览器不行，划词点击图标没有翻译，窗口翻译也没反应
![image](https://user-images.githubusercontent.com/9413415/68448545-cd02ab00-021e-11ea-9f63-e7e9d72c4bf4.png)

**Comment by yzhang-gh** [comment]
1.2.16 版本，每次刷新页面之后可以正常查几个词，过一会就不行了

看后台报错应该和搜狗验证码有关

![image](https://user-images.githubusercontent.com/7588612/69496237-f7d14c80-0f0a-11ea-9522-be5901cd593d.png)

**Comment by swxca** [comment]
又不行了？2020年03月26日19:07:12

**Comment by Ti800** [comment]
sougou频繁需要验证（4，5个词就会触发），且当前https://translate.google.cn 在代理情况下无法访问，从而导致翻译没反应。

**Comment by swxca** [comment]
@Ti800 https://translate.google.cn我这边不挂代理也不能访问

**Comment by tli47** [comment]
> sougou频繁需要验证（4，5个词就会触发），且当前https://translate.google.cn 在代理情况下无法访问，从而导致翻译没反应。

Same issue with me ...

**Comment by Yansongsongsong** [comment]
cant active extension with `alt + shift + d` in local file path mode.
在打开本地pdf文件的时候，只能通过选中右键翻译，其他的方式均失效

**Comment by IM1T** [comment]
![image](https://user-images.githubusercontent.com/30109898/83110569-d9385200-a0f5-11ea-839c-a9b5a282dab9.png)
裂开

**Comment by yinxulai** [comment]
![image](https://user-images.githubusercontent.com/22045569/83368549-c9698800-a3eb-11ea-995d-512fa8d8cff6.png)
![image](https://user-images.githubusercontent.com/22045569/83368558-d5554a00-a3eb-11ea-8fe3-97e46ddb94e3.png)

**Comment by waynecz** [comment]
各位，因为最近搜狗又升级了下反爬手段，加上谷歌加强了对插件的审查严格度，导致我最近一次的发布被拒而且最近在找工作没时间更新（懒），所以要不大家先去用 [沙拉查词吧 ！](https://chrome.google.com/webstore/detail/%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D-%E8%81%9A%E5%90%88%E8%AF%8D%E5%85%B8%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/cdonnmffkdaoajfknoeeecmchibpmkmg?hl=zh-CN)  等我修复了上线了再来通知大家，大家遇到这问题的可以先不用急着卸载插件，等下次更新好了插件也就自然的好了
![image](https://user-images.githubusercontent.com/11238540/83218296-5ae4ba00-a1a0-11ea-9c16-dc36eb0319f5.png)

**Comment by SeekingLight233** [comment]
> 各位，因为最近搜狗又升级了下反爬手段，加上谷歌加强了对插件的审查严格度，导致我最近一次的发布被拒而且最近在找工作没时间更新（懒），所以要不大家先去用 [沙拉查词吧 ！](https://chrome.google.com/webstore/detail/%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D-%E8%81%9A%E5%90%88%E8%AF%8D%E5%85%B8%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/cdonnmffkdaoajfknoeeecmchibpmkmg?hl=zh-CN) 等我修复了上线了再来通知大家，大家遇到这问题的可以先不用急着卸载插件，等下次更新好了插件也就自然的好了
> ![image](https://user-images.githubusercontent.com/11238540/83218296-5ae4ba00-a1a0-11ea-9c16-dc36eb0319f5.png)

作者辛苦了！我觉得实在不行的话设置面板里加个入口允许使用搜狗翻译的PID。。。
![image](https://user-images.githubusercontent.com/44890048/85554941-fc541400-b657-11ea-89f3-4031bc3eecc4.png)

**Comment by Icedroid** [comment]
请问修复了吗？还是不能使用

**Comment by ppooii12009** [comment]
![FWMOS)EB7TT0P~_)AKRV3IR](https://user-images.githubusercontent.com/30223176/86362257-95fa7180-bca7-11ea-9591-182ff44e47c3.png)
如图  划词翻译无响应

**Comment by yyyzt** [comment]
在新版edge没有任何反应

**Comment by Andesome** [comment]
![image](https://user-images.githubusercontent.com/15965343/91965852-a7153c80-ed43-11ea-8e7a-142ccbd80344.png)
翻译没反应。

**Comment by youngjuning** [comment]
翻译没反应

**Comment by wildwolf19998** [comment]
两台电脑的翻译都跳不出来

**Comment by cctv1005s** [comment]
😅 我觉得我还能救一下这个插件，等我这周末搞一下和百度集成一下，用百度的免费额度翻译好了

下面是我本地直接改的结果，我打算开一个口子让大家可以设置百度的开发者秘钥，这样就能直接调用了

![image](https://user-images.githubusercontent.com/16508727/153547289-94b9f4de-0f8a-42e1-800f-a0691c3cd96e.png)



---
放张二维码，如果我整好了我还会再回来的
![image](https://user-images.githubusercontent.com/16508727/153547382-32a3f1b3-4c60-4845-8f2d-eb162979b275.png)

**Comment by Perruer** [comment]
大家好！达达的搜狗/扇贝接口已经失效，原作者也不再维护了。我基于达达（MIT 协议）重写了一个 Manifest V3 版本 WordToast，保留了划词翻译、生词本和「吐司弹词」复习的思路：

- 翻译引擎：Google 翻译（默认，失败时自动切换到 MyMemory）、DeepL、Chrome 本地离线翻译，也可以接入自己的 AI 模型（OpenAI / Claude / Gemini / Ollama 等）
- 浏览器语言是中文时会自动翻译成中文
- 生词本保存单词所在的句子，可导出到 Anki / CSV
- 支持 Chrome、Edge、Firefox

目前界面只有英文和俄文，中文界面在计划中。欢迎试用和反馈：
https://github.com/Perruer/wordtoast

(EN) Dadda's Sogou/Shanbay APIs are gone. WordToast is a maintained Manifest V3 rewrite of Dadda (MIT): selection translation into your browser language (Chinese works), wordbook with context and Anki export, review toasts, Google/DeepL/on-device/your own AI. Chrome, Edge, Firefox.
